spring:
  datasource:
    url: jdbc:postgresql://dpg-d0be7915pdvs73cjehlg-a.frankfurt-postgres.render.com:5432/uvitodb
    username: postgresvito
    password: HyC09SxxbSHCNzAHDBWWJLWiOGSnSMCd
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: F:\Downloads\Study\Uvito\src\main\resources\static
  resources:
    static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
