spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Uvito
    username: postgres
    password: 3311
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: ./uploads/images/
  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
