spring:
  datasource:
    url: jdbc:postgresql://db:5432/Uvito
    username: postgres
    password: 3311
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: F:\Downloads\Study\Uvito\src\main\resources\static
  resources:
    static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
